### ISSUE TITLE
Catalog 만들기 - Standalone product 

### ISSUE THREAD

**Issue by jinyoung** [TheOpenCloudEngine/killbill#4]
Addon / Standalone (product type) 처리
- addon 을 등록해주기 위하여 Catalog XML을 동적으로 변경하여 다시 deploy 시키는 기능이 필요
 ** Add-on 에 대하여 BASE 와 통합된 invoice 내에 넣어서 줌.
- Standalone 으로 10000개 정도의 상품이 디플로이되고 과금하는데 성능저하가 없는지부터확인

**Comment by SeungpilPark** [comment]
카달로그 플러그인 예제
[https://github.com/killbill/killbill-catalog-plugin-test](https://github.com/killbill/killbill-catalog-plugin-test)

킬빌이 카달로그를 불러올 때,
1. bundle 폴더 내의 등록된 카달로그의 플러그인을 찾음.
2. 만약 카달로그 플러그인이 있다면, 킬빌이 이 플러그인을 실행시켜 봐서 카달로그 객체가 리턴된다면 리턴된 카달로그 객체를 사용함.  우리는 이 플러그인에 다음을 개발해야 함.
   ㄱ.  플러그인을 호출한 테넌트 정보 및 기존 카달로그 정보를 API 를 통해 킬빌로부터 받을 수 있음.
   ㄴ.  우리가 만들 어플리케이션쪽으로 테넌트에 대한 addon 정보를 요청하여 받아옴.
   ㄷ.  플러그인에서는 기존 Base 카달로그 + addon 정보를 조합하여, 카달로그 자바 객체를 생성해서 리턴해줌.
         (bpm 프로세스 데피니션을 동적으로 생성하는 것과 같은 개념)
   ㄹ.  주의: 이 플러그인이 카달로그 객체를 리턴하더라고 킬빌의 카달로그 캐쉬가 업데이트 되지는 않음. 이 플러그인은 매우 빈번하게 호출될것이기 때문에, (매 스케쥴링 타임마다 로드) 이 플러그인 내부에 캐쉬로직을 직접 구현해야 퍼포먼스를 낼 수 있음. 즉 우리 어플리케이션 측에서 addon 정보가 업데이트 될 때 이 플러그인이 알 수 있도록 해야함.  
   ㄹ 의 증빙 자료:  [http://docs.killbill.io/0.18/catalog_plugin.html](http://docs.killbill.io/0.18/catalog_plugin.html)

  The main use case, is the one where there is already a catalog service used outside of Kill Bill. The goal of the plugin is to interract with that existing service and map the results into a format compatible with the Kill Bill abstraction by implementing the CatalogPluginApi. Of course, if the models are very different this can be a challenging (or impossible) task to achieve.

3. 결과적으로 킬빌의 Base Standalone Catalog 를 유지하면서  플러그인을 통한 Extend Catalog 를 사용할 수 있음.  단,  인보이스가 과연 플러그인을 통해 리턴된 카달로그 베이스로 작성될지,  Base Standalone Catalog 를 기준으로 작성될지는 소스코드를 통해 추적중에 있음.
